title: "Jekyll build demo action"

source: .
destination: ./_site

exclude:
  [
    "src",
    "types",
    "tools",
    "package.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "README.md",
    "tsconfig.json",
    "tsconfig.node.json",
    "vite.config.ts"
  ]

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false
