name: Jekyll site CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Project build
        run: |
          yarn install
          yarn run build:jekyll

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c "\
              chmod -R 777 /srv/jekyll && \
              jekyll build\
          "

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: webgl-gol-build-artifact
          path: ${{ github.workspace }}/_site
          if-no-files-found: error

  # Push the build results to the gh-pages branch where it will be automatically processed.
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: webgl-gol-build-artifact
          path: ${{ github.workspace }}/_site

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ${{ github.workspace }}/repo

      - name: Push build artifact to gh-pages
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

          cd /repo
          git rm -rf
          git clean -fxd
          mv ../_site/* .
          git add *
          git commit -m "Automatic commit"
          git push origin gh-pages
