name: WebGL Auto-deployment

# When workflow will run.
on:
  # Triggers on push or pull request events for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows the workflow to be manually run from the Actions tab.
  workflow_dispatch:

# The workflow is a build job followed by a deploy job.
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Project build
        run: |
          npm install
          npm run build:github
          cp README.md docs/index.md
          cp license.txt docs/license.txt
          rm .gitignore

      - name: Push docs/ content to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Removed unless build artifacts are needed later
      # - name: Build the site in the jekyll/builder container
      #   run: |
      #     docker run \
      #       -v ${{ github.workspace }}/docs:/srv/jekyll \
      #       -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
      #       jekyll/builder:latest /bin/bash -c "\
      #         chmod -R 777 /srv/jekyll && \
      #         jekyll build --config ./tools/_config.yml\
      #     "

      # - name: Upload jekyll build result as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: webgl-gol-build-artifact
      #     path: ${{ github.workspace }}/_site
      #     if-no-files-found: error
